### ISSUE TITLE
Is it possible to get Last Raven working?

### ISSUE THREAD

**Issue by mekanisk** [marcellusparley/ac-emblem-tool#1]
Hi. First of all, let me say thank you for making this. I was playing through the old Armored Core games again and I was amazed someone actually made something like this. I'm still on Silent Line right now, but I thought I'd test out if the tool works with Last Raven ahead of time. Unfortunately, it looks like the emblem data from Last Raven may be formatted differently, because I was given the "Save file is too small" error when trying to run it through the tool. Any help getting it to work would be greatly appreciated, and thank you again for your work. :)

**Comment by mparley** [comment]
Thanks. Yeah I was working on this when I played through the series and when I got burnt out sometime during silent line this project went to the wayside. I never got around to trying it on the later games. I'll take a crack at it but it might take until after the holidays/new year. In the mean time it looks like someone made a converter for last raven a while ago: https://ravenrepublic.net/forums/showthread.php?mode=linear&tid=3307&pid=7882148  - I haven't tried it myself yet but if it works you won't have to hold up your play through waiting on me. I should also check if it works on nexus and nine breaker. I guess with the announcement of AC6 now is a good time to fix/finish this project

**Comment by mparley** [comment]
I ended up downloading Last Raven and taking a peek at it's emblem saves. It wasn't too different from the others so I went ahead and did it. The only downside is that it has to be the dataX file itself and not within some other filetype like those old ps2 save transfer formats. But as long as you can extract the data file from the format or use the pcsx2 folder structure you should be able to do it.

**Comment by mekanisk** [comment]
Awesome dude, that was fast as hell. Thanks a bunch 👍
