### ISSUE TITLE
AC2 (USA) Broken File

### ISSUE THREAD

**Issue by rodriguezjulianf** [marcellusparley/ac-emblem-tool#2]
I tried to inject a png 128x128 with decreased colors from this tool https://onlinepngtools.com/decrease-png-color-count and with a pcsx2 savefile, i'm on windows 10 btw.
The tool runs fine but when I try to load the emblem ingame, it shows up as broken file and cannot be loaded: 
![imagen](https://github.com/mparley/ac-emblem-tool/assets/75989926/9c5f1eb6-8b9d-4401-9116-bf2a8de735cc)
![imagen](https://github.com/mparley/ac-emblem-tool/assets/75989926/61da3301-2a2e-4a0a-af12-baade5fc4056)

Am I missing something important or it's a known issue?

**Comment by mparley** [comment]
I tried that online converter a handful of times just now and got weird results, but mostly the output pngs would be blocked for having too many colors even though I set the color count to less than 255. The few that did work (very low colors) seemed to transfer to the game ok. 

Admittedly I probably didn't test thoroughly enough when making this and there is probably some dumb bug I missed that messes up the color count. I usually take images I want as emblems and use something like GIMP or ImageMagick to downscale and palettize the emblem though the tool is supposed to work with any 128x128 32bit RGBA PNG.

However usually when the game can't read an emblem save or it says it's broken it means there is some formatting problem with the save. Usually something messed up with the checksums. If you extract the image from the altered emblem save (drag and drop just the save on the tool) does the extracted image match the one you injected or is it all garbled up? If possible could you attach the image you injected, the backup save, and the altered save?

**Comment by kairusds** [comment]
@mparley this is off-topic but for mine i just converted it to png8 which worked perfectly with the tool and loaded up just fine. changing an image's depth might not be the best option (i think)

**Comment by kairusds** [comment]
@mparley this is off-topic but for mine i just converted it to png8 with imagemagick which worked perfectly with the tool and loaded up just fine

**Comment by rodriguezjulianf** [comment]
[acet.zip](https://github.com/mparley/ac-emblem-tool/files/11587196/acet.zip)
This are the files i'm using. The .png is a png8 done with imagemagick. The savefile extracted image is fine too.

**Comment by rodriguezjulianf** [comment]
Sorry for closing the issue I missclicked.
I modified an image with imagemagick, did resize to 128x128 and converted to png8 and still my ps2file is broken. Extracting the image from the save works fine, image isn't broken.
I will send you via Discord the .zip with the image and the saves.

**Comment by mparley** [comment]
Alright, my discord is biodigitaljazz#6824 -- at least until they get around to switching me to the new @ usernames. I'll try taking a look at it

**Comment by rodriguezjulianf** [comment]
Finally it was my bad. I was using the tool on the wrong file and didn't do anything. Sorry for the trouble and thanks for the help!
